#!/bin/bash

# run this command:
# source run

# Check if a stock symbol was provided
if [ -z "$1" ]; then
    echo "Usage: $0 <stock_symbol>"
    return
fi

# Set the symbol variable from the first command line argument
SYMBOL="$1"
SAFE_SYMBOL="${SYMBOL//\//|}"
HTML_FILE="./output/${SAFE_SYMBOL}.html"

source ./bin/activate

./download.sh "${SYMBOL}"
TICKER="${SAFE_SYMBOL}" jupyter nbconvert --to html --output "${HTML_FILE}" run.ipynb
python extract_images.py "${HTML_FILE}"
open "./output/${SAFE_SYMBOL}.png"